version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_icoffee_database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ICoffee"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
  goAPi:
    image: 'golang:latest'
    container_name: 'golang-ICoffee'
    volumes: 
      - .:/go/src/ICoffee
    working_dir: /go/src/ICoffee



